#!/bin/sh

# print a list of redundant forms - words w/o flags that are generated by other words with flags

# Usage: check_words.sh dictionary affixfile
# Needs ready dictionary and affix files, ispell and buildhash
# Recommended usage: make YO=1 dict.koi oldrussian.aff; check_words.sh dict.koi oldrussian.aff
# Prints the list of redundant words w/o flags
# Note that the C,D flags are NOT to be included for this test

[ "x$2" = x ] && {
	echo Usage: `basename $0` dictionary_file affix_file
	exit
}

tmp="checkwords.tmpdir"
origdir="`pwd`"
rm -rf "$tmp"
mkdir -p "$tmp"
echo "Preparing temporary data..." 1>&2
cat "$1" | perl -e 'while(<STDIN>){if (/^[^\/]+$/) {print;} else {print STDERR;}}' > "$tmp/woflags" 2> "$tmp/withflags"
cp "$2" "$tmp/thisaffix"
cd "$tmp"
buildhash -s withflags thisaffix tmp.hash
echo "Generating word list..." 1>&2
ispell -W 0 -l -d ./tmp.hash < woflags > result
cd "$origdir"
#cat ./redundant.koi >> "$tmp/result"
cat "$tmp/woflags" | ./excludelines.pl "$tmp/result" -quiet
# Clean up
rm -rf "$tmp"
