#!/bin/sh
# sort a file in Cyrillic koi8-r encoding alphabetically
# Original file from rus-ispell
# Changes by Serge Winitzki: add old Russian letters and more options
#
# Usage: sortkoi8c [-f] [-r] [-s] < input > output
# -f Fold lower case characters into the equivalent upper case
#    characters when sorting so that, for example, `B' is greater
#    than `a' (without `-f', uppercase characters precede lowercase).
# -r Sort in reverse order
# -s Sort by suffix rather than by prefix

ALPH='áâ÷çäå²³öúé¶±êëìíîïğòóôõæ¼èãşûıÿùøüàñÁÂ×ÇÄÅ¢£ÖÚÉ¦¡ÊËÌÍÎÏĞÒÓÔÕÆ¬ÈÃŞÛİßÙØÜÀÑ'
# Default options
suffix=no
fold=""
reverse=""
perlreverse='undef $/; print scalar reverse <>;';

while test x"$1" != x
do
case x"$1" in
x-f)
fold="-f"
ALPH='áÁâÂ÷×çÇäÄåÅ²¢³£öÖúÚéÉ¶¦±¡êÊëËìÌíÍîÎïÏğĞòÒóÓôÔõÕæ¼Æ¬èÈãÃşŞûÛıİÿßùÙøØüÜàÀñÑ'
;;
x-r)
if test x"$reverse" = x
then
reverse="-r"
else
reverse=""
fi
;;
x-s)
suffix=yes
if test x"$reverse" = x
then
reverse="-r"
else
reverse=""
fi
;;
*)
;;
esac
shift
done

TEMP='¡¢£¦¬±²³¶¼ÀÁÂÃÄÅÆÇÈÉÊËÌÍÎÏĞÑÒÓÔÕÖ×ØÙÚÛÜİŞßàáâãäåæçèéêëìíîïğñòóôõö÷øùúûüışÿ'
if test "$suffix" = "yes"
then

perl -e "$perlreverse" | tr $ALPH $TEMP | LC_COLLATE=POSIX sort $fold $reverse | tr $TEMP $ALPH | perl -e "$perlreverse"

else

tr $ALPH $TEMP | LC_COLLATE=POSIX sort $fold $reverse | tr $TEMP $ALPH

fi
