#!/bin/sh

set -e

ourname=oldrussian

while [ "$1" != "" ]
do
 case "$1" in
  upgrade) upgrade="Yes" ;;
  remove) remove="Yes" ;;
 esac
 shift
done

if [ -n "$remove" ]
then
 if [ -n "`update-alternatives --display ispell-dictionary.hash \
	| grep $ourname | grep 999`" ]
 then
  update-alternatives --remove ispell-dictionary.hash 		\
	/usr/lib/ispell/$ourname.hash > /dev/null
  update-ispell-dictionary
 else
  update-alternatives --remove ispell-dictionary.hash 		\
	/usr/lib/ispell/$ourname.hash > /dev/null
 fi
fi
